id: 4d329c1a2a3e40dcac5e6103dccef5d5
initial_creation_type: TMX
origin_type: null
source_metadata:
  id: ''
  title: Toh_179-Teaching_The_Relative_and_Ultimate_Truths-v1
  language: bo
  author: ''
  volume: {}
